/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_josuevidal;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeNode;

/**
 *
 * @author josue
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Proyecto = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombreProyecto = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jd_Actividad = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreActividad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sp_duracionActividad = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        sp_retrasoActividad = new javax.swing.JSpinner();
        cb_proyectosActividades = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_predecesoras = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jd_play = new javax.swing.JDialog();
        pgb_time = new javax.swing.JProgressBar();
        jlb_nombre = new javax.swing.JLabel();
        jlb_time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cb_proyectos = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        jLabel7.setText("Proyecto");

        jLabel8.setText("Nombre:");

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ProyectoLayout = new javax.swing.GroupLayout(jd_Proyecto.getContentPane());
        jd_Proyecto.getContentPane().setLayout(jd_ProyectoLayout);
        jd_ProyectoLayout.setHorizontalGroup(
            jd_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProyectoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(178, 178, 178))
            .addGroup(jd_ProyectoLayout.createSequentialGroup()
                .addGroup(jd_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ProyectoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ProyectoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton4)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jd_ProyectoLayout.setVerticalGroup(
            jd_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addGroup(jd_ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(25, 25, 25))
        );

        jLabel1.setText("Nombre:");

        jLabel2.setText("Actividad");

        jLabel3.setText("Duracion:");

        sp_duracionActividad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel4.setText("Retraso:");

        sp_retrasoActividad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        cb_proyectosActividades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_proyectosActividadesItemStateChanged(evt);
            }
        });
        cb_proyectosActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_proyectosActividadesActionPerformed(evt);
            }
        });

        jLabel5.setText("Proyecto:");

        jLabel6.setText("Predecesora:");

        jButton3.setText("Crear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jl_predecesoras.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_predecesoras);

        jButton6.setText("Cargar actividades");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ActividadLayout = new javax.swing.GroupLayout(jd_Actividad.getContentPane());
        jd_Actividad.getContentPane().setLayout(jd_ActividadLayout);
        jd_ActividadLayout.setHorizontalGroup(
            jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ActividadLayout.createSequentialGroup()
                .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ActividadLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel2))
                    .addGroup(jd_ActividadLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton3)
                                .addComponent(tf_nombreActividad)
                                .addGroup(jd_ActividadLayout.createSequentialGroup()
                                    .addComponent(sp_duracionActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(sp_retrasoActividad, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                .addComponent(cb_proyectosActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jd_ActividadLayout.setVerticalGroup(
            jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nombreActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sp_duracionActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(sp_retrasoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_proyectosActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addGroup(jd_ActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(37, 37, 37))
        );

        jlb_nombre.setText("jLabel10");

        jlb_time.setText("jLabel11");

        javax.swing.GroupLayout jd_playLayout = new javax.swing.GroupLayout(jd_play.getContentPane());
        jd_play.getContentPane().setLayout(jd_playLayout);
        jd_playLayout.setHorizontalGroup(
            jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_playLayout.createSequentialGroup()
                        .addComponent(jlb_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlb_time))
                    .addComponent(pgb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jd_playLayout.setVerticalGroup(
            jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_playLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jd_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_nombre)
                    .addComponent(jlb_time))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgb_time, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Proyecto");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jButton1.setText("Crear Proyecto");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Actividad");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton5.setText("Cargar arbol");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel9.setText("Primero seleccione un Proyecto para ver en el arbol");

        jButton7.setText("Ejecutar Proyecto");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel10.setText("Si una actividad sale como nodo es por que puede ser predecesora");

        jButton8.setText("Eliminar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_proyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(cb_proyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton7)
                        .addGap(24, 24, 24)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jd_Proyecto.setModal(true);
        jd_Proyecto.pack();
        jd_Proyecto.setLocationRelativeTo(this);
        jd_Proyecto.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jd_Actividad.setModal(true);
        jd_Actividad.pack();
        jd_Actividad.setLocationRelativeTo(this);
        jd_Actividad.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        int duracion = 0;
        Proyecto p = new Proyecto(duracion, tf_nombreProyecto.getText());
        Proyectos.add(p);
        cb_proyectos.addItem(p);
        cb_proyectosActividades.addItem(p.getNombre());

    }//GEN-LAST:event_jButton4MouseClicked

    private void cb_proyectosActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_proyectosActividadesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_proyectosActividadesActionPerformed

    private void cb_proyectosActividadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_proyectosActividadesItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_proyectosActividadesItemStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int inicio;

        int ind = cb_proyectosActividades.getSelectedIndex();
        Proyecto project = Proyectos.get(ind);
        if (project.getActividades().isEmpty()) {
            inicio = 1;
        } else {

            for (int i = 0; i < project.getActividades().size(); i++) {
                int aux = project.getActividades().get(i).getFinal_temprano();
                if (aux > mayor) {
                    mayor = aux;
                }
            }
            inicio = mayor + 1;
        }

        int final_temprano = inicio + (int) sp_duracionActividad.getValue();
        int ind2 = jl_predecesoras.getSelectedIndex();
        Actividades a = new Actividades(tf_nombreActividad.getText(), inicio, (int) sp_duracionActividad.getValue(), final_temprano, (int) sp_retrasoActividad.getValue());
        if (project.getActividades().isEmpty()) {

        } else {
            try {
                a.addPredecesoras(project.getActividades().get(ind2));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "esta actividad no se encuentra en el mismo proyecto");
            }

        }
        duracion+=(int)sp_duracionActividad.getValue();
        project.getActividades().add(a);
        System.out.println(project);
        System.out.println(a);


    }//GEN-LAST:event_jButton3MouseClicked
    Proyecto global;
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        global = cb_proyectos.getItemAt(cb_proyectos.getSelectedIndex());

        DefaultMutableTreeNode root = new DefaultMutableTreeNode(global);
        asignarSucesoras();
        listar_tree(global.getActividades(), root);
        DefaultMutableTreeNode root2 = new DefaultMutableTreeNode(global);
        tirar_arreglo(global.getActividades(), root2);
        DefaultTreeModel m = new DefaultTreeModel(root);
        root.remove(root.getChildCount() - 1);
        jTree1.setModel(m);


    }//GEN-LAST:event_jButton5MouseClicked
    ArrayList<Actividades> activities = new ArrayList();

    public void tirar_arreglo(ArrayList<Actividades> p, DefaultMutableTreeNode nodo) {
        try {

            for (Actividades temp : p) {

                if (temp.getPredecesoras().isEmpty()) {
                    boolean ver = false;
                    for (Actividades t : activities) {
                        if (temp.getNombre().equals(t.getNombre())) {
                            ver = true;
                        }

                    }
                    if (!ver) {
                        activities.add(temp);

                    }

                } else {

                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getNombre());
                    nodo.add(n);
                    boolean ver = false;
                    for (Actividades t : activities) {
                        if (temp.getNombre().equals(t.getNombre())) {
                            ver = true;
                        }

                    }
                    if (!ver) {
                        activities.add(temp);

                    }
                    listar_tree(temp.getPredecesoras(), n);

                }

            }
        } catch (Exception e) {
        }
    }

    public void listar_tree(ArrayList<Actividades> p, DefaultMutableTreeNode nodo) {
        try {

            for (Actividades temp : p) {

                if (temp.getSucesoras().isEmpty() && temp.getPredecesoras().size() < 1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getNombre());
                    nodo.add(n);
                    System.out.println("hice");

                } else {

                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getNombre());
                    nodo.add(n);
                    System.out.println("hiceeldos");
                    listar_tree(temp.getSucesoras(), n);

                }

            }
        } catch (Exception e) {
        }

    }


    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        if (cb_proyectosActividades.getSelectedIndex() >= 0) {
            DefaultListModel modelo = new DefaultListModel();

            ArrayList<Actividades> act = new ArrayList();
            int ind = cb_proyectosActividades.getSelectedIndex();
            Proyecto project = Proyectos.get(ind);
            act = project.getActividades();
            if (act.size() < 0) {

            } else {
                for (int i = 0; i < act.size(); i++) {
                    modelo.addElement(act.get(i));
                }
            }
            jl_predecesoras.setModel(modelo);
        }
    }//GEN-LAST:event_jButton6MouseClicked
    private void asignarSucesoras() {
        for (Proyecto t : Proyectos) {
            for (Actividades z : t.getActividades()) {
                for (Actividades x : t.getActividades()) {
                    if (z.getPredecesoras().isEmpty()) {

                    } else if (z.getPredecesoras().get(0).getNombre().equals(x.getNombre()) && !x.getNombre().equals(z.getNombre())) {
                        boolean ver = false;
                        for (Actividades sucesora : Proyectos.get(Proyectos.indexOf(t)).getActividades().get(t.getActividades().indexOf(x)).getSucesoras()) {
                            if (sucesora.getNombre().equals(z.getNombre())) {
                                ver = true;
                            }
                        }
                        if (!ver) {
                            Proyectos.get(Proyectos.indexOf(t)).getActividades().get(t.getActividades().indexOf(x)).addSucesoras(z);

                        }
                    }
                }
            }

        }
    }
    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        Tabla t = new Tabla();
        t.setVisible(true);
        t.table1.setVisible(true);
        at = new adminTabla(activities, cb_proyectos.getSelectedItem().toString(), t.table1);
        TD = new Thread(at);
        at.start();

        jlb_nombre.setText(cb_proyectos.getSelectedItem().toString());
        pgb_time.setMaximum(duracion);
        jd_play.pack();
        jd_play.setLocationRelativeTo(this);
        jd_play.setVisible(true);
        hh = new HiloActividad(jlb_time, duracion, pgb_time);
        hh.start();
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
         DefaultMutableTreeNode n = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        Proyecto temp = null;
        for (Proyecto P : Proyectos) {
            if (P.getNombre().equals(n.toString())) {
                temp = P;
            }
        }
        Proyectos.remove(temp);
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_proyectos.getModel();
        m.removeElement(temp);
        jTree1.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("")));

    }//GEN-LAST:event_jButton8MouseClicked
    private void CargarArbol(ArrayList<Actividades> Root, DefaultMutableTreeNode nodo) {
        /*
        try {
            for (Actividades temp : Root) {
                if (temp.getPredecesoras().isEmpty()) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getNombre());
                    nodo.add(n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(temp.getNombre());
                    nodo.add(n);
                    SetTrees(temp.getAfter(), n);
                }
                if (Root.toString().equals(nombreraiz)) {
                    break;
                }
            }
        } catch (Exception e) {
        }
         */
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Proyecto> cb_proyectos;
    private javax.swing.JComboBox<String> cb_proyectosActividades;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JDialog jd_Actividad;
    private javax.swing.JDialog jd_Proyecto;
    private javax.swing.JDialog jd_play;
    private javax.swing.JList<String> jl_predecesoras;
    private javax.swing.JLabel jlb_nombre;
    private javax.swing.JLabel jlb_time;
    private javax.swing.JProgressBar pgb_time;
    private javax.swing.JSpinner sp_duracionActividad;
    private javax.swing.JSpinner sp_retrasoActividad;
    private javax.swing.JTextField tf_nombreActividad;
    private javax.swing.JTextField tf_nombreProyecto;
    // End of variables declaration//GEN-END:variables
    ArrayList<Proyecto> Proyectos = new ArrayList();
    int mayor = 0;
    ArrayList<Actividades> predecesoras = new ArrayList();
    HiloActividad hh;
    adminTabla at;
    Thread TD;
    int duracion=0;
}
